name: Integração Contínua

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Instalar Dependências
        run: |
          npm install 
          npm install -g nodemon

      - name: Iniciar Aplicação com Nodemon
        run: nodemon index.js &

      - name: Esperar a Inicialização
        run: sleep 10 

      - name: Rodar Testes
        run: npm run test 